version: '3'
services:
  web:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      env_file:
        .env
      depends_on:
        - db
        - redis
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
    volumes:
      - /c/Users/Sam/Repositories/sr-skilltest/.env:/app/.env
  redis:
    image: redis:latest
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_POST: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redisdata:/data
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  pgdata:
  redisdata:
  jenkins_data: