version: '3'
services:
  web:
      container_name: full_app
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
      - api:/usr/src/app/
      ports:
        - "8080:8080"
      env_file:
        .env
      depends_on:
        - db
        - redis
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fullstack
  redis:
    image: redis:latest
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_POST: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redisdata:/data
    networks:
      - fullstack
volumes:
  api:
  pgdata:
  redisdata:
# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
