version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
      DATABASE_HOST: ${SQL_HOST}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - fullstack
    restart: always
  redis:
    image: redis:latest
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    networks:
      - fullstack
  app:
    container_name: full_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - api:/usr/src/app/
    ports:
      - "8080:8080"
    env_file:
      .env
    restart: always
    depends_on:
      - postgres
      - redis
    networks:
      - fullstack
volumes:
  api:
  pgdata:
  redisdata:
# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
